# Generated by Django 5.1.2 on 2024-11-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
